### ISSUE TITLE
Fix HTTPError resulting from notion-py's HTTP upload limit setting

### ISSUE THREAD

**Issue by ikezue** [projectstake/git-notion#3]
This could be fixed by downgrading or upgrading notion-py.

See https://github.com/NarekA/git-notion/pull/5.

**Comment by Steph-crown** [comment]
This error can be fixed by updating the settings locally,

- Run `pip show notion` in your terminal. This displays info, including the location of the `notion` package in your machine.
- Get the location of the Notion package

```
...
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
...
```

- Navigate to this folder, open the `notion/store.py` file, and change `"limit": 100000,` on line **280** to `"limit": 100,`.

- Save the file and try to run the command again. It should work this time.

**Comment by ikezue** [comment]
It would be best to fix it once, for all users. See my earlier comment.

**Comment by Steph-crown** [comment]
To fix this error, first uninstall the previously installed `notion` package. 

```
pip uninstall notion  
```

Then install the dependencies (including `notion`) directly from the `requirements.in` file. 
```
 pip install -r requirements.in
```

This installs the modified version of `notion` from this [repo](https://github.com/knightjoel/notion-py). I'd suggest that we also have our own fork of that version. 

At this point, the `git-notion` command can be run without any hiccups.
